### ISSUE TITLE
Quartus programming issue

### ISSUE THREAD

**Issue by malek-75** [olofk/fusesoc#309] opened 2019-11-07 13:18 UTC
In the stable version of fusesoc (sudo  pip install) :  Invoking quartus tool generates an error  
NameError : global name '**remaining**' is not defined.

**remaining** variable is referenced to as an argument in run_main function, quartus.py (edalize) : 
 
This issue doesn't appear in the development version (installed from git)

**Comment by olofk** [comment] 2019-11-07 14:00
I see it now. Technically, the issue is in Edalize rather than FuseSoC but in any case, there is no stable version of Edalize with this fix. I have released version 0.1.7 of Edalize now. Please try `pip install -U edalize` and see if it works after an upgrade

**Comment by malek-75** [comment] 2019-11-07 15:01
Yes it works !
Furthermore, I noticed - in the same file - that a '**board_device_index'** was added to '**the tool_options**'. I guess it concerns boards within a soc as DE1SoC. I will test this and come back to you.
Thanks.

**Comment by olofk** [comment] 2019-11-07 17:26
Yes, that is exactly the reason. See https://github.com/fusesoc/blinky/pull/8 :)

Ok to close this one?

**Comment by malek-75** [comment] 2019-11-08 08:22
Yes.
Thank you.

**Closed** 2019-11-08 11:19 UTC
